spring:
  application:
    name: vanke-ioc-audit

    #默认使用配置
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9999

  ##自定义日志路径,日志存储目录
logging:
  path: E:\\vanke-ioc-audit-logs

  #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
      typeAliasesPackage: com.vanke
      mapperLocations: classpath:mapper/*.xml
